 dist: trusty

 language: java

 jdk:
   - oraclejdk8

 cache:
   directories:
     - $HOME/.m2
     - ./frontend/node_modules/
     - $HOME/.sonar
     - $HOME/.sonarscanner

 before_script:
   - npm install --prefix ./frontend/


 script:
    - mvn clean test
    - npm run build --prefix ./frontend/
    - sonar-scanner

    addons:
      sonarcloud:
        organization: zuuras-github
        token: 6726fb8b0d3eeaf6e55ac1bf26b88a4c2b25e308